// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Choice.H>

class AppNavUI {
public:
  AppNavUI();
};
#endif
