// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "MainWindow.h"

AppNavUI::AppNavUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 520, "Auto Nav");
    w = o; (void)w;
    o->user_data((void*)(this));
    { Fl_Output* o = new Fl_Output(0, 10, 600, 22, "AirplaneTitle");
      o->box(FL_FLAT_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NO_LABEL);
      o->align(Fl_Align(FL_ALIGN_CENTER));
    } // Fl_Output* o
    { new Fl_Button(20, 58, 115, 70, "Connect");
    } // Fl_Button* o
    { new Fl_Button(168, 58, 115, 70, "AP");
    } // Fl_Button* o
    { Fl_Counter* o = new Fl_Counter(17, 164, 120, 25, "Airspeed");
      o->minimum(0);
      o->step(1);
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Counter* o
    { new Fl_Button(20, 211, 115, 30, "Airspeed hold");
    } // Fl_Button* o
    { new Fl_Button(20, 251, 115, 30, "Auto throttle");
    } // Fl_Button* o
    { new Fl_Button(316, 211, 115, 70, "ALT");
    } // Fl_Button* o
    { Fl_Counter* o = new Fl_Counter(311, 164, 120, 25, "Altitude");
      o->minimum(0);
      o->step(100);
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Counter* o
    { new Fl_Button(309, 487, 122, 22, "Test position");
    } // Fl_Button* o
    { new Fl_Button(461, 487, 122, 22, "Refresh @refresh");
    } // Fl_Button* o
    { Fl_Output* o = new Fl_Output(15, 480, 122, 22, "Altitude manually adjustable");
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Output* o
    { new Fl_Button(316, 301, 115, 70, "Approach");
    } // Fl_Button* o
    { new Fl_Button(465, 58, 115, 70, "FLC");
    } // Fl_Button* o
    { new Fl_Button(316, 58, 115, 70, "Flight Director");
    } // Fl_Button* o
    { new Fl_Button(170, 301, 115, 70, "NAV");
    } // Fl_Button* o
    { new Fl_Button(465, 301, 115, 70, "Wing LVL");
    } // Fl_Button* o
    { new Fl_Button(22, 301, 115, 70, "Yaw Damper");
    } // Fl_Button* o
    { new Fl_Button(168, 251, 115, 30, "Heading locked");
    } // Fl_Button* o
    { Fl_Counter* o = new Fl_Counter(165, 164, 120, 25, "Heading");
      o->minimum(-1);
      o->maximum(360);
      o->step(1);
      o->value(360);
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Counter* o
    { Fl_Output* o = new Fl_Output(46, 397, 122, 22, "Heading adjustable");
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Output* o
    { new Fl_Button(465, 211, 115, 70, "VS");
    } // Fl_Button* o
    { Fl_Counter* o = new Fl_Counter(463, 164, 120, 25, "Vertical speed");
      o->minimum(0);
      o->maximum(0);
      o->step(100);
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Counter* o
    { Fl_Choice* o = new Fl_Choice(168, 217, 115, 22, "Heading Index");
      o->down_box(FL_BORDER_BOX);
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Choice* o
    o->resizable(o);
    o->end();
  } // Fl_Double_Window* o
}
